name: "kms"
services:
  app:
    image: "Claudiomfa/kms:1.3.1"
    environment:
      TZ: "Europe/Lisbon"
    volumes:
      - "var:/kms/var"
    ports:
      - "1688:1688/tcp"
    restart: "always"

  gui:
    image: "Claudiomfa/kms-gui:latest"
    depends_on:
      app:
        condition: "service_healthy"
        restart: true
    environment:
      TZ: "Europe/Lisbon"
    volumes:
      - "var:/kms/var"
    ports:
      - "3000:3000/tcp"
    restart: "always"

volumes:
  var:
